/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javatimeejercicio;

import java.time.DayOfWeek;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Month;
import java.time.Period;
import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;
import java.time.temporal.TemporalAdjusters;
import javax.swing.JLabel;

/**
 *
 * @author frank
 */
public class JavaTime extends javax.swing.JFrame {

    /**
     * Creates new form JavaTime
     */
    public JavaTime() {
        initComponents();
        // fechaActual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JLabelFechaActual = new javax.swing.JLabel();
        jLabelHoraActual = new javax.swing.JLabel();
        jLabelFechaHoraActual = new javax.swing.JLabel();
        jLabelInstanteActual = new javax.swing.JLabel();
        jLabelFechaHoraZonaHorario = new javax.swing.JLabel();
        jLabelCumpleanios = new javax.swing.JLabel();
        jLabelHoraExacta = new javax.swing.JLabel();
        jLabelFecha10Dias = new javax.swing.JLabel();
        jLabelFechaHora32Horas = new javax.swing.JLabel();
        jLabelPrimerDiaProxMes = new javax.swing.JLabel();
        jLabelUltimoDiasMesActual = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelMesesDiasFindeAnio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ejercicio Java Time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jLabel2.setText("Fecha Actual es :");

        jLabel3.setText("La Hora Actual es:");

        jLabel4.setText("La Fecha y Hora Actual es:");

        jLabel5.setText("El Instante Actual es:");

        jLabel6.setText("La Fecha y Hora Actuales con Zona Horario son:");

        jLabel7.setText("Fecha de mi Cumpleanios:");

        jLabel8.setText("Con la Hora Exacta:");

        jLabel9.setText("La Fecha Dentro de 10 Dias");

        jLabel10.setText("La Fecha y Hora de Hace 32 Horas");

        jLabel11.setText("El Primer Dia del Proximo Mes");

        jLabel12.setText("Ultimo Dia del Mes Actual:");

        jLabel13.setText("Tu edad es (years):");

        jLabel14.setText("Faltan ( Meses ) y (Dias) para el fin de anio:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        JLabelFechaActual.setText("---------");

        jLabelHoraActual.setText("---------");

        jLabelFechaHoraActual.setText("---------");

        jLabelInstanteActual.setText("---------");

        jLabelFechaHoraZonaHorario.setText("---------");

        jLabelCumpleanios.setText("---------");

        jLabelHoraExacta.setText("---------");

        jLabelFecha10Dias.setText("---------");

        jLabelFechaHora32Horas.setText("---------");

        jLabelPrimerDiaProxMes.setText("---------");

        jLabelUltimoDiasMesActual.setText("---------");

        jLabelEdad.setText("---------");

        jLabelMesesDiasFindeAnio.setText("---------");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMesesDiasFindeAnio)
                    .addComponent(jLabelEdad)
                    .addComponent(jLabelUltimoDiasMesActual)
                    .addComponent(jLabelPrimerDiaProxMes)
                    .addComponent(jLabelFechaHora32Horas)
                    .addComponent(jLabelFecha10Dias)
                    .addComponent(jLabelHoraExacta)
                    .addComponent(jLabelCumpleanios)
                    .addComponent(jLabelFechaHoraZonaHorario)
                    .addComponent(jLabelInstanteActual)
                    .addComponent(jLabelFechaHoraActual)
                    .addComponent(jLabelHoraActual)
                    .addComponent(JLabelFechaActual))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(JLabelFechaActual)
                .addGap(18, 18, 18)
                .addComponent(jLabelHoraActual)
                .addGap(18, 18, 18)
                .addComponent(jLabelFechaHoraActual)
                .addGap(18, 18, 18)
                .addComponent(jLabelInstanteActual)
                .addGap(18, 18, 18)
                .addComponent(jLabelFechaHoraZonaHorario)
                .addGap(18, 18, 18)
                .addComponent(jLabelCumpleanios)
                .addGap(18, 18, 18)
                .addComponent(jLabelHoraExacta)
                .addGap(18, 18, 18)
                .addComponent(jLabelFecha10Dias)
                .addGap(18, 18, 18)
                .addComponent(jLabelFechaHora32Horas)
                .addGap(18, 18, 18)
                .addComponent(jLabelPrimerDiaProxMes)
                .addGap(18, 18, 18)
                .addComponent(jLabelUltimoDiasMesActual)
                .addGap(18, 18, 18)
                .addComponent(jLabelEdad)
                .addGap(18, 18, 18)
                .addComponent(jLabelMesesDiasFindeAnio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Ejecucion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        fechaActual();
        horaActual();
        fechaHoraActual();
        Instante();
        FechaHoraZona();
        Cumpleanios();
        Cumpleaniosconhora();
        Fecha10Dias();
        FechaHora32();
        PrimerDiaProxMes();
        UltimoDiaMes();
        Edad();
        HastaFinal();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaTime().setVisible(true);
            }
        });
    }

    public void fechaActual() {
        LocalDate fechaAhora = LocalDate.now();
        JLabelFechaActual.setText(fechaAhora.toString());
        System.out.println("Fecha Actual " + fechaAhora);
    }

    public void horaActual() {
        LocalTime horaAhora = LocalTime.now();
        jLabelHoraActual.setText(horaAhora.toString());
        System.out.println("Fecha Actual " + horaAhora);
    }

    public void fechaHoraActual() {
        /* LocalTime horaAhora = LocalTime.now();
        LocalDate fechaAhora = LocalDate.now();
        jLabelFechaHoraActual.setText("Fecha= " + fechaAhora + "      " + "Hora= " + horaAhora.toString());
        System.out.println("Fecha Actual = " + fechaAhora + "   " + "Hora Actual = " + horaAhora);*/
        ZonedDateTime fechaHoraZona = ZonedDateTime.now();
        jLabelFechaHoraZonaHorario.setText(fechaHoraZona.toString());

    }

    public void Instante() {
        Instant instante = Instant.now();
        jLabelInstanteActual.setText(instante.toString());
        System.out.println("Instante= " + instante);
    }

    public void FechaHoraZona() {
        LocalTime horaAhora = LocalTime.now();
        LocalDate fechaAhora = LocalDate.now();
        jLabelFechaHoraActual.setText("Fecha= " + fechaAhora + "      " + "Hora= " + horaAhora.toString());
        System.out.println("Fecha Actual = " + fechaAhora + "   " + "Hora Actual = " + horaAhora);
    }

    public void Cumpleanios() {
        LocalDate cumpleanios = LocalDate.of(2003, Month.MARCH, 20);
        jLabelCumpleanios.setText(cumpleanios.toString());
    }

    public void Cumpleaniosconhora() {
        LocalDateTime cumpleaniosHora = LocalDateTime.of(2003, Month.MARCH, 20, 20, 20, 39);
        jLabelHoraExacta.setText(cumpleaniosHora.toString());
    }

    public void Fecha10Dias() {
        LocalDate fecha10 = LocalDate.now().plusDays(10);
        jLabelFecha10Dias.setText(fecha10.toString());
    }

    public void FechaHora32() {
        LocalDateTime fechaHora32 = LocalDateTime.now().minusHours(32);
        jLabelFechaHora32Horas.setText(fechaHora32.toString());
    }

    public void PrimerDiaProxMes() {

        LocalDate fechadiaprox = LocalDate.now().with(TemporalAdjusters.firstDayOfNextMonth());
        DayOfWeek primerDiaProx = LocalDate.now().with(TemporalAdjusters.firstDayOfNextMonth()).getDayOfWeek();

        jLabelPrimerDiaProxMes.setText("Dia= " + primerDiaProx + "  " + "Fecha= " + fechadiaprox.toString());
    }

    public void UltimoDiaMes() {
        DayOfWeek DultimoDiaMes = LocalDate.now().with(TemporalAdjusters.lastDayOfMonth()).getDayOfWeek();
        LocalDate ultimoDiaMes = LocalDate.now().with(TemporalAdjusters.lastDayOfMonth());
        jLabelUltimoDiasMesActual.setText(DultimoDiaMes + "   " + ultimoDiaMes.toString());
    }

    public void Edad() {
        LocalDate edad = LocalDate.of(2003, Month.MARCH, 20);
        //jLabelEdad.setText(ChronoUnit.YEARS.between(edad, LocalDate.now()));
        System.out.println("Edad " + ChronoUnit.YEARS.between(edad, LocalDate.now()));
        jLabelEdad.setText("Edad " + ChronoUnit.YEARS.between(edad, LocalDate.now()));
    }
    
    public void HastaFinal(){
        LocalDate hoy = LocalDate.now();
        LocalDate findeanio = hoy.with(TemporalAdjusters.lastDayOfYear());
        Period hastafinanio = hoy.until(findeanio);
        int meses = hastafinanio.getMonths();
        int dias = hastafinanio.getDays();
        jLabelMesesDiasFindeAnio.setText("Faltan " +meses+ " meses y " + dias + " Dias Hasta fin de anio" );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelFechaActual;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCumpleanios;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFecha10Dias;
    private javax.swing.JLabel jLabelFechaHora32Horas;
    private javax.swing.JLabel jLabelFechaHoraActual;
    private javax.swing.JLabel jLabelFechaHoraZonaHorario;
    private javax.swing.JLabel jLabelHoraActual;
    private javax.swing.JLabel jLabelHoraExacta;
    private javax.swing.JLabel jLabelInstanteActual;
    private javax.swing.JLabel jLabelMesesDiasFindeAnio;
    private javax.swing.JLabel jLabelPrimerDiaProxMes;
    private javax.swing.JLabel jLabelUltimoDiasMesActual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
